all:
  hosts:
    board:
      ansible_host: <SERVER_IP>
      ansible_port: <SSH_SERVER_PORT>
      ansible_private_key_file: <SSH_SERVER_PRIVATE_KEY>
      ansible_user: <SSH_SERVER_USER>
      ansible_become: true
      description: CTFd board server