---

- name: "Wait for CTFd to come up"
  uri:
    url: "http://127.0.0.1:80/"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1

- name: Restore game from backup
  community.docker.docker_container_exec:
    container: ctf_ctfd_1
    command: /bin/bash -c "python manage.py import_ctf backup.zip"
  register: result

- name: Print stdout
  debug:
    var: result.stdout